version: '3.3'
services:
  bookstack:
    image: linuxserver/bookstack:${SOFTWARE_VERSION_TAG}
    environment:
      - PUID=1001
      - PGID=1001
      - APP_URL=${APP_URL}
      - APP_KEY=${APP_KEY}
      - DB_HOST=db
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_DATABASE=bookstackapp
      - MAIL_DRIVER=smtp
      - MAIL_FROM_NAME="BookStack"
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_HOST=172.17.0.1
      - MAIL_PORT=25
      - MAIL_ENCRYPTION=null
      - MAIL_VERIFY_SSL=false
    volumes:
      - ./web:/config
    ports:
      - '172.17.0.1:6875:80'
    restart: always
    depends_on:
      - db
  db:
    image: linuxserver/mariadb
    environment:
      - PUID=1001
      - PGID=1001
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./mariadb:/config
    restart: always
